config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: main
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/rizac/eGSIM:
      branch: main
      repo: https://github.com/rizac/eGSIM.git
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/rizac/eGSIM git:
        commands:
        - /usr/bin/env sh .sqa/script.surly-saffron-sparrow.sh
        container: qc.acc_surly-tan-caterpillar
  QC.Doc:
    repos:
      github.com/rizac/eGSIM find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.gloppy-indigo-terrier.sh
        container: qc.doc_geeky-zucchini-penguin
      github.com/rizac/eGSIM git:
        commands:
        - /usr/bin/env sh .sqa/script.surly-ruby-rabbit.sh
        container: qc.doc_thirsty-red-newfoundland
      github.com/rizac/eGSIM markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.snippy-burgundy-birman.sh
        container: qc.doc_jumpy-wisteria-axolotl
  QC.Lic:
    repos:
      github.com/rizac/eGSIM licensee:
        commands:
        - /usr/bin/env sh .sqa/script.slimy-tangerine-schnauzer.sh
        container: qc.lic_sickly-cobalt-ragdoll
  QC.Sec:
    repos:
      github.com/rizac/eGSIM bandit:
        commands:
        - /usr/bin/env sh .sqa/script.dorky-firebrick-flamingo.sh
        container: qc.sec_queasy-cerise-fly
  QC.Sty:
    repos:
      github.com/rizac/eGSIM flake8:
        commands:
        - /usr/bin/env sh .sqa/script.shaggy-corn-butterfly.sh
        container: qc.sty_snazzy-violet-mule
      github.com/rizac/eGSIM jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.skanky-platinum-emu.sh
        container: qc.sty_scummy-violet-pinscher
  QC.Uni:
    repos:
      github.com/rizac/eGSIM pytest:
        commands:
        - /usr/bin/env sh .sqa/script.gimpy-blue-eel.sh
        container: qc.uni_droopy-carmine-swan
  QC.Ver:
    repos:
      github.com/rizac/eGSIM get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.goopy-razzmatazz-frigatebird.sh
        container: qc.ver_trippy-harlequin-goat
timeout: 5400
